//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/PlayerControls/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""158de193-8d9a-46de-bffe-45f10a2db564"",
            ""actions"": [
                {
                    ""name"": ""BlinkSkill"",
                    ""type"": ""Button"",
                    ""id"": ""92628783-416a-401a-8fe7-07e6da2ff647"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QSkill"",
                    ""type"": ""Button"",
                    ""id"": ""3c274068-7e19-451c-9b46-dbcdc9765468"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ESkill"",
                    ""type"": ""Button"",
                    ""id"": ""d44e6cb1-9f68-4c5d-85e9-57077859df57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMouseButton"",
                    ""type"": ""Button"",
                    ""id"": ""33f0f9de-2677-4f71-b57b-725596f3418a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMouseButton"",
                    ""type"": ""Button"",
                    ""id"": ""d7f841a3-a048-428f-a794-b6ed54cc6888"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSlots"",
                    ""type"": ""Value"",
                    ""id"": ""f1db5fe9-cc0e-44f4-b71f-dae54328b50b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MMBPress"",
                    ""type"": ""Button"",
                    ""id"": ""6f3a6a27-5782-49a3-b21a-9ae5601405f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MMBScroll"",
                    ""type"": ""Button"",
                    ""id"": ""4ab8a25b-d8fa-411c-ba2f-6a125342f298"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8f441968-1b2f-4e20-870b-628770fbb883"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BlinkSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b119dc8d-9176-45e5-9d44-d9771ac5a303"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ESkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bee4ebc-ad92-4bee-832d-d756e785fc2b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b01ff300-1b79-4f59-8112-782187048265"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54caeb3b-a8c2-47a8-af20-b8d65864c122"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlots"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7ef4ffb-111e-44dd-a26a-65895400e8b5"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlots"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9245f079-5a77-49b7-a098-6dc1261f9ce2"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlots"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00c17561-d1a4-4e89-b841-6334cc9ece79"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlots"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b661f5c1-d367-4322-8fc9-b05bf30e1686"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9116e5dc-a9db-4280-975e-63491cb43e96"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MMBPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Scroll"",
                    ""id"": ""c29241d5-00b7-475b-9857-dcdbd16e38b7"",
                    ""path"": ""1DAxis(whichSideWins=1)"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(min=-1,max=1)"",
                    ""groups"": """",
                    ""action"": ""MMBScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b1a3b60a-4dfc-4785-a201-4283e1e5cf14"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MMBScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ad5027ee-d1f9-445e-bc96-a347388098e8"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MMBScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_BlinkSkill = m_Player.FindAction("BlinkSkill", throwIfNotFound: true);
        m_Player_QSkill = m_Player.FindAction("QSkill", throwIfNotFound: true);
        m_Player_ESkill = m_Player.FindAction("ESkill", throwIfNotFound: true);
        m_Player_LeftMouseButton = m_Player.FindAction("LeftMouseButton", throwIfNotFound: true);
        m_Player_RightMouseButton = m_Player.FindAction("RightMouseButton", throwIfNotFound: true);
        m_Player_QuickSlots = m_Player.FindAction("QuickSlots", throwIfNotFound: true);
        m_Player_MMBPress = m_Player.FindAction("MMBPress", throwIfNotFound: true);
        m_Player_MMBScroll = m_Player.FindAction("MMBScroll", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_BlinkSkill;
    private readonly InputAction m_Player_QSkill;
    private readonly InputAction m_Player_ESkill;
    private readonly InputAction m_Player_LeftMouseButton;
    private readonly InputAction m_Player_RightMouseButton;
    private readonly InputAction m_Player_QuickSlots;
    private readonly InputAction m_Player_MMBPress;
    private readonly InputAction m_Player_MMBScroll;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @BlinkSkill => m_Wrapper.m_Player_BlinkSkill;
        public InputAction @QSkill => m_Wrapper.m_Player_QSkill;
        public InputAction @ESkill => m_Wrapper.m_Player_ESkill;
        public InputAction @LeftMouseButton => m_Wrapper.m_Player_LeftMouseButton;
        public InputAction @RightMouseButton => m_Wrapper.m_Player_RightMouseButton;
        public InputAction @QuickSlots => m_Wrapper.m_Player_QuickSlots;
        public InputAction @MMBPress => m_Wrapper.m_Player_MMBPress;
        public InputAction @MMBScroll => m_Wrapper.m_Player_MMBScroll;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @BlinkSkill.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlinkSkill;
                @BlinkSkill.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlinkSkill;
                @BlinkSkill.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlinkSkill;
                @QSkill.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQSkill;
                @QSkill.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQSkill;
                @QSkill.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQSkill;
                @ESkill.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnESkill;
                @ESkill.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnESkill;
                @ESkill.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnESkill;
                @LeftMouseButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftMouseButton;
                @LeftMouseButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftMouseButton;
                @LeftMouseButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftMouseButton;
                @RightMouseButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightMouseButton;
                @RightMouseButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightMouseButton;
                @RightMouseButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightMouseButton;
                @QuickSlots.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuickSlots;
                @QuickSlots.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuickSlots;
                @QuickSlots.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuickSlots;
                @MMBPress.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMMBPress;
                @MMBPress.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMMBPress;
                @MMBPress.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMMBPress;
                @MMBScroll.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMMBScroll;
                @MMBScroll.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMMBScroll;
                @MMBScroll.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMMBScroll;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @BlinkSkill.started += instance.OnBlinkSkill;
                @BlinkSkill.performed += instance.OnBlinkSkill;
                @BlinkSkill.canceled += instance.OnBlinkSkill;
                @QSkill.started += instance.OnQSkill;
                @QSkill.performed += instance.OnQSkill;
                @QSkill.canceled += instance.OnQSkill;
                @ESkill.started += instance.OnESkill;
                @ESkill.performed += instance.OnESkill;
                @ESkill.canceled += instance.OnESkill;
                @LeftMouseButton.started += instance.OnLeftMouseButton;
                @LeftMouseButton.performed += instance.OnLeftMouseButton;
                @LeftMouseButton.canceled += instance.OnLeftMouseButton;
                @RightMouseButton.started += instance.OnRightMouseButton;
                @RightMouseButton.performed += instance.OnRightMouseButton;
                @RightMouseButton.canceled += instance.OnRightMouseButton;
                @QuickSlots.started += instance.OnQuickSlots;
                @QuickSlots.performed += instance.OnQuickSlots;
                @QuickSlots.canceled += instance.OnQuickSlots;
                @MMBPress.started += instance.OnMMBPress;
                @MMBPress.performed += instance.OnMMBPress;
                @MMBPress.canceled += instance.OnMMBPress;
                @MMBScroll.started += instance.OnMMBScroll;
                @MMBScroll.performed += instance.OnMMBScroll;
                @MMBScroll.canceled += instance.OnMMBScroll;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnBlinkSkill(InputAction.CallbackContext context);
        void OnQSkill(InputAction.CallbackContext context);
        void OnESkill(InputAction.CallbackContext context);
        void OnLeftMouseButton(InputAction.CallbackContext context);
        void OnRightMouseButton(InputAction.CallbackContext context);
        void OnQuickSlots(InputAction.CallbackContext context);
        void OnMMBPress(InputAction.CallbackContext context);
        void OnMMBScroll(InputAction.CallbackContext context);
    }
}
